apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: node-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: node-demo
  template:
    metadata:
      labels:
        app: node-demo
    spec:
      containers:
      - name: node-app
        image: node-k8s-demo:v2
        ports:
        - containerPort: 3000
