apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-volume
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-volume-demo
  template:
    metadata:
      labels:
        app: node-volume-demo
    spec:
      containers:
        - name: node-app
          image: node-k8s-demo:config-v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

          # Basic env vars
          env:
            - name: PORT
              value: "8080"

          # Mount ConfigMap as volume
          volumeMounts:
            - name: config-volume
              mountPath: /etc/config # Mount path in container
              readOnly: true

      volumes:
        - name: config-volume
          configMap:
            name: node-app-config
