apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-secret-volume
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-secret-volume
  template:
    metadata:
      labels:
        app: node-secret-volume
    spec:
      containers:
        - name: node-app
          image: node-k8s-demo:config-v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

          volumeMounts:
            # Mount secrets as files
            - name: secret-volume
              mountPath: /etc/secrets
              readOnly: true

            # Mount config
            - name: config-volume
              mountPath: /etc/config
              readOnly: true

      volumes:
        - name: secret-volume
          secret:
            secretName: app-secrets
            defaultMode: 0400 # Read-only for owner

        - name: config-volume
          configMap:
            name: node-app-config
