apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-selective
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-selective-demo
  template:
    metadata:
      labels:
        app: node-selective-demo
    spec:
      containers:
        - name: node-app
          image: node-k8s-demo:config-v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

          volumeMounts:
            - name: config-volume
              mountPath: /etc/config

      volumes:
        - name: config-volume
          configMap:
            name: node-app-config
            items: # Select specific keys
              - key: app.properties
                path: application.properties # Rename the file
              - key: features.json
                path: features.json
