apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-secret-envfrom
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-secret-envfrom
  template:
    metadata:
      labels:
        app: node-secret-envfrom
    spec:
      containers:
        - name: node-app
          image: node-k8s-demo:config-v1
          imagePullPolicy: Never

          # Import all from ConfigMap
          envFrom:
            - configMapRef:
                name: node-app-config

            # Import all from Secret
            - secretRef:
                name: app-secrets
