apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-with-secrets
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-secrets-demo
  template:
    metadata:
      labels:
        app: node-secrets-demo
    spec:
      containers:
        - name: node-app
          image: node-k8s-demo:config-v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

          env:
            # From ConfigMap
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: node-app-config
                  key: PORT

            # From Secret
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: database-password

            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: app-secrets
                  key: api-key
