apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-envfrom
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-envfrom-demo
  template:
    metadata:
      labels:
        app: node-envfrom-demo
    spec:
      containers:
        - name: node-app
          image: node-k8s-demo:config-v1
          imagePullPolicy: Never
          ports:
            - containerPort: 8080

          # Method 2: Import ALL keys from ConfigMap
          envFrom:
            - configMapRef:
                name: node-app-config

          # Can also add individual env vars
          env:
            - name: FEATURE_NEW_UI
              value: "true"
