apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
  labels:
    app: node-demo
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1        # Max extra Pods during update
      maxUnavailable: 1  # Max Pods down during update
  selector:
    matchLabels:
      app: node-demo
  template:
    metadata:
      labels:
        app: node-demo
        version: v1
    spec:
      containers:
      - name: node-app
        image: node-k8s-demo:v1
        imagePullPolicy: Never
        ports:
        - containerPort: 3000

